In [11]:
import torch
from IPython.core.interactiveshell import InteractiveShell

InteractiveShell.ast_node_interactivity = "all" # type: ignore

x = torch.tensor([1, 2, 3, 4])
x.unsqueeze(0)
x.unsqueeze(1)

y = torch.tensor([[1, 1], [2, 2]])
y
y.unsqueeze(0)
y.unsqueeze(1)
y.unsqueeze(2)

tensor([[1, 2, 3, 4]])

tensor([[1],
        [2],
        [3],
        [4]])

tensor([[1, 1],
        [2, 2]])

tensor([[[1, 1],
         [2, 2]]])

tensor([[[1, 1]],

        [[2, 2]]])

tensor([[[1],
         [1]],

        [[2],
         [2]]])